CREATE INDEX "archived_service_data_original_id_idx" ON "archived_service_data" USING btree ("original_id");--> statement-breakpoint
CREATE INDEX "archived_service_data_user_id_idx" ON "archived_service_data" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "archived_service_data_archive_reason_idx" ON "archived_service_data" USING btree ("archive_reason");--> statement-breakpoint
CREATE INDEX "archived_service_data_archived_at_idx" ON "archived_service_data" USING btree ("archived_at");--> statement-breakpoint
CREATE INDEX "archived_service_data_service_type_idx" ON "archived_service_data" USING btree ("service_type");--> statement-breakpoint
CREATE INDEX "customer_profiles_user_id_idx" ON "customer_profiles" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "customer_profiles_created_at_idx" ON "customer_profiles" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "email_verifications_user_id_idx" ON "email_verifications" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "email_verifications_expires_at_idx" ON "email_verifications" USING btree ("expires_at");--> statement-breakpoint
CREATE INDEX "email_verifications_is_used_expires_at_idx" ON "email_verifications" USING btree ("is_used","expires_at");--> statement-breakpoint
CREATE INDEX "expert_profiles_user_id_idx" ON "expert_profiles" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "expert_profiles_created_at_idx" ON "expert_profiles" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "users_role_idx" ON "users" USING btree ("role");--> statement-breakpoint
CREATE INDEX "users_is_approved_idx" ON "users" USING btree ("is_approved");--> statement-breakpoint
CREATE INDEX "users_is_banned_idx" ON "users" USING btree ("is_banned");--> statement-breakpoint
CREATE INDEX "users_is_email_verified_idx" ON "users" USING btree ("is_email_verified");--> statement-breakpoint
CREATE INDEX "users_created_at_idx" ON "users" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "users_role_approved_idx" ON "users" USING btree ("role","is_approved");--> statement-breakpoint
CREATE INDEX "sessions_user_id_idx" ON "sessions" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "sessions_expires_at_idx" ON "sessions" USING btree ("expires_at");--> statement-breakpoint
CREATE INDEX "sessions_user_id_expires_at_idx" ON "sessions" USING btree ("user_id","expires_at");--> statement-breakpoint
CREATE INDEX "legal_agreements_user_id_idx" ON "legal_agreements" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "legal_agreements_agreement_name_idx" ON "legal_agreements" USING btree ("agreement_name");--> statement-breakpoint
CREATE INDEX "legal_agreements_accepted_at_idx" ON "legal_agreements" USING btree ("accepted_at");--> statement-breakpoint
CREATE INDEX "service_data_user_id_idx" ON "service_data" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "service_data_assigned_expert_id_idx" ON "service_data" USING btree ("assigned_expert_id");--> statement-breakpoint
CREATE INDEX "service_data_status_idx" ON "service_data" USING btree ("status");--> statement-breakpoint
CREATE INDEX "service_data_service_type_idx" ON "service_data" USING btree ("service_type");--> statement-breakpoint
CREATE INDEX "service_data_created_at_idx" ON "service_data" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "service_data_user_status_idx" ON "service_data" USING btree ("user_id","status");--> statement-breakpoint
CREATE INDEX "service_data_expert_status_idx" ON "service_data" USING btree ("assigned_expert_id","status");--> statement-breakpoint
CREATE INDEX "quote_negotiations_quote_id_idx" ON "quote_negotiations" USING btree ("quote_id");--> statement-breakpoint
CREATE INDEX "quote_negotiations_service_request_id_idx" ON "quote_negotiations" USING btree ("service_request_id");--> statement-breakpoint
CREATE INDEX "quote_negotiations_sender_id_idx" ON "quote_negotiations" USING btree ("sender_id");--> statement-breakpoint
CREATE INDEX "quote_negotiations_created_at_idx" ON "quote_negotiations" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "service_payments_service_request_id_idx" ON "service_payments" USING btree ("service_request_id");--> statement-breakpoint
CREATE INDEX "service_payments_customer_id_idx" ON "service_payments" USING btree ("customer_id");--> statement-breakpoint
CREATE INDEX "service_payments_quote_id_idx" ON "service_payments" USING btree ("quote_id");--> statement-breakpoint
CREATE INDEX "service_payments_status_idx" ON "service_payments" USING btree ("status");--> statement-breakpoint
CREATE INDEX "service_payments_paid_at_idx" ON "service_payments" USING btree ("paid_at");--> statement-breakpoint
CREATE INDEX "service_quotes_service_request_id_idx" ON "service_quotes" USING btree ("service_request_id");--> statement-breakpoint
CREATE INDEX "service_quotes_customer_id_idx" ON "service_quotes" USING btree ("customer_id");--> statement-breakpoint
CREATE INDEX "service_quotes_admin_id_idx" ON "service_quotes" USING btree ("admin_id");--> statement-breakpoint
CREATE INDEX "service_quotes_status_idx" ON "service_quotes" USING btree ("status");--> statement-breakpoint
CREATE INDEX "service_quotes_created_at_idx" ON "service_quotes" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "service_quotes_customer_status_idx" ON "service_quotes" USING btree ("customer_id","status");--> statement-breakpoint
CREATE INDEX "quiz_attempts_user_id_idx" ON "quiz_attempts" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "quiz_attempts_quiz_id_idx" ON "quiz_attempts" USING btree ("quiz_id");--> statement-breakpoint
CREATE INDEX "quiz_attempts_is_completed_idx" ON "quiz_attempts" USING btree ("is_completed");--> statement-breakpoint
CREATE INDEX "quiz_attempts_user_quiz_idx" ON "quiz_attempts" USING btree ("user_id","quiz_id");--> statement-breakpoint
CREATE INDEX "quiz_attempts_started_at_idx" ON "quiz_attempts" USING btree ("started_at");--> statement-breakpoint
CREATE INDEX "quiz_questions_quiz_id_idx" ON "quiz_questions" USING btree ("quiz_id");--> statement-breakpoint
CREATE INDEX "quiz_questions_quiz_id_order_idx" ON "quiz_questions" USING btree ("quiz_id","order_index");--> statement-breakpoint
CREATE INDEX "quiz_templates_created_by_idx" ON "quiz_templates" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX "quiz_templates_created_at_idx" ON "quiz_templates" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "quizzes_created_by_idx" ON "quizzes" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX "quizzes_template_id_idx" ON "quizzes" USING btree ("template_id");--> statement-breakpoint
CREATE INDEX "quizzes_is_published_idx" ON "quizzes" USING btree ("is_published");--> statement-breakpoint
CREATE INDEX "quizzes_is_archived_idx" ON "quizzes" USING btree ("is_archived");--> statement-breakpoint
CREATE INDEX "quizzes_target_audience_idx" ON "quizzes" USING btree ("target_audience");--> statement-breakpoint
CREATE INDEX "quizzes_published_archived_idx" ON "quizzes" USING btree ("is_published","is_archived");--> statement-breakpoint
CREATE INDEX "quizzes_created_at_idx" ON "quizzes" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "learning_modules_created_by_idx" ON "learning_modules" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX "learning_modules_category_idx" ON "learning_modules" USING btree ("category");--> statement-breakpoint
CREATE INDEX "learning_modules_target_audience_idx" ON "learning_modules" USING btree ("target_audience");--> statement-breakpoint
CREATE INDEX "learning_modules_is_published_idx" ON "learning_modules" USING btree ("is_published");--> statement-breakpoint
CREATE INDEX "learning_modules_is_archived_idx" ON "learning_modules" USING btree ("is_archived");--> statement-breakpoint
CREATE INDEX "learning_modules_order_index_idx" ON "learning_modules" USING btree ("order_index");--> statement-breakpoint
CREATE INDEX "learning_modules_published_archived_idx" ON "learning_modules" USING btree ("is_published","is_archived");--> statement-breakpoint
CREATE INDEX "learning_progress_user_id_idx" ON "learning_progress" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "learning_progress_module_id_idx" ON "learning_progress" USING btree ("module_id");--> statement-breakpoint
CREATE INDEX "learning_progress_material_id_idx" ON "learning_progress" USING btree ("material_id");--> statement-breakpoint
CREATE INDEX "learning_progress_user_module_idx" ON "learning_progress" USING btree ("user_id","module_id");--> statement-breakpoint
CREATE INDEX "learning_progress_is_completed_idx" ON "learning_progress" USING btree ("is_completed");--> statement-breakpoint
CREATE INDEX "learning_progress_last_accessed_idx" ON "learning_progress" USING btree ("last_accessed");--> statement-breakpoint
CREATE INDEX "module_materials_module_id_idx" ON "module_materials" USING btree ("module_id");--> statement-breakpoint
CREATE INDEX "module_materials_module_id_order_idx" ON "module_materials" USING btree ("module_id","order_index");--> statement-breakpoint
CREATE INDEX "module_materials_material_type_idx" ON "module_materials" USING btree ("material_type");--> statement-breakpoint
CREATE INDEX "trainer_resources_is_published_idx" ON "trainer_resources" USING btree ("is_published");--> statement-breakpoint
CREATE INDEX "trainer_resources_created_by_idx" ON "trainer_resources" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX "trainer_resources_category_idx" ON "trainer_resources" USING btree ("category");--> statement-breakpoint
CREATE INDEX "trainer_resources_resource_type_idx" ON "trainer_resources" USING btree ("resource_type");--> statement-breakpoint
CREATE INDEX "trainer_resources_created_at_idx" ON "trainer_resources" USING btree ("created_at");